name: Maven snapshot

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      - name: Set version
        id: version
        run: |
          git fetch --prune --unshallow
          shopt -s nocasematch
          if [[ "${{github.event_name}}" == "pull_request" ]]; then
            ref="${{github.head_ref}}"
            node_regex="node-([0-9]+)-.*"
            sc_regex="sc-([0-9]+)-.*"
            if [[ $ref =~ $node_regex ]]; then
              issue="${BASH_REMATCH[1]}"
              prefix="N"
            elif [[ $ref =~ $sc_regex ]]; then
              issue="${BASH_REMATCH[1]}"
              prefix="SC"
            else
              echo "$ref doesnt match node-1111-smth regex"
              exit 1
            fi
            version="$prefix$issue"
            if test -z "$version"; then exit 1; fi
            ./setversion.sh "$version"
          else
            mvn_version=$(grep -Eo '<version>(.*)</version>' pom.xml | head -1)
            version=$(./setversion.sh snapshot)
            if [[ $mvn_version != "<version>$version</version>" ]]; then
              echo "Incorrect version set: $mvn_version, should be $version"
              exit 1
            fi
          fi
      - name: Release Maven package
        uses: samuelmeuli/action-maven-publish@v1.4.0
        with:
          gpg_private_key: ${{ secrets.gpg_private_key }}
          gpg_passphrase: ${{ secrets.gpg_passphrase }}
          nexus_username: ${{ secrets.nexus_username }}
          nexus_password: ${{ secrets.nexus_password }}